#!/bin/bash
set -e
## goto script directory
cd $(dirname $0)

## debug option
if [[ $1 == "debug" ]]; then
  DEBUG="-DCMAKE_BUILD_TYPE=Debug"
  echo $DEBUG
fi

BUILD_DIR='build'
if [ ! -d ${BUILD_DIR} ];then
  mkdir ${BUILD_DIR}
fi

cd ${BUILD_DIR}

if [ ! -f Makefile ] || [ ../CMakeLists.txt -nt Makefile ]
then
  cmake $DEBUG ..
fi

make

cd ..

BIN=$(grep "project" CMakeLists.txt | head -1 | sed 's/project (\(.*\))/\1/')

mv ${BUILD_DIR}/${BIN} .
